### ISSUE TITLE
CircleCI Partner Review

### ISSUE THREAD

**Issue by EricRibeiro** [Rezilion/rezilion-circleci-orb#1]
Hello Rezilion team 👋

I am from the @circleci Community and Partner Engineering team, here to help with a review for the CircleCI orb partnership. I have a few items listed below for changes:

- Include a link to the mentioned guide.

Please include a link in the [parameter description](https://github.com/Rezilion/rezilion-circleci-orb/blob/main/src/jobs/validate.yml#L9) to help users find it faster.

- Use the same default for command and job parameters.

Unless there is a reason for doing otherwise, the default value for your [command](https://github.com/Rezilion/rezilion-circleci-orb/blob/main/src/commands/rezilion_start.yml#L6) and [job](https://github.com/Rezilion/rezilion-circleci-orb/blob/main/src/jobs/validate.yml#L8) should be the same.

- Fix the stdout and stderr redirections.

Assuming that's what you are trying to do [here](https://github.com/Rezilion/rezilion-circleci-orb/blob/main/src/scripts/install_rezilion.sh#L7), [here](https://github.com/Rezilion/rezilion-circleci-orb/blob/main/src/scripts/install_rezilion.sh#L11) and [here](https://github.com/Rezilion/rezilion-circleci-orb/blob/main/src/scripts/install_rezilion.sh#L18), the proper way of doing is with`&>`  instead of `>`. See section [3.6.4](https://www.gnu.org/software/bash/manual/html_node/Redirections.html).

- Improve the installation script.

Your installation script has a few redundant lines, and it lacks error messages. I'm leaving a suggestion below but feel free to modify it as you wish.

```
REZILION_EXECUTABLE_URL="https://validate-ci-instrument.s3.eu-west-1.amazonaws.com/validate_ci_agent_v2.0"
REZILION_OUTPUTS_FOLDER=/tmp/rezilion/outputs
REZILION_AGENT_PATH=/tmp/rezilion/validate_ci_agent

mkdir -p $REZILION_OUTPUTS_FOLDER

# curl isn't installed
if ! command -v curl &> /dev/null; then
  # install curl with apt-get
  if command -v apt-get &> /dev/null; then
    apt-get update
    apt-get install curl -y

  # install curl with yum
  elif command -v yum &> /dev/null; then
    yum install curl -y
  
  else
    echo "Impossible to install Rezilion without curl. Please install it and try again."
    exit 1
  fi
fi

curl -s $REZILION_EXECUTABLE_URL --output $REZILION_AGENT_PATH
chmod +x $REZILION_AGENT_PATH
```

- What is the Rezilion stop command?

The [description](https://github.com/Rezilion/rezilion-circleci-orb/blob/main/src/commands/rezilion_stop.yml#L2) says:

> Stops rezilion over the container

But the only thing is doing is persisting a folder to the workspace. Is there something missing from this command?

**Comment by amitrezilion** [comment]
Hey Eric,
Thanks for the review, we have some notes:

 Regarding "What is the Rezilion stop command", on all our ci environments we use start and stop commands, and because we want to have a consistent semantic, we keep the name, even though we don't need to stop rezilion. in the future, we'll add logic to the stop command, and we don't want to change the orb usage.

**Comment by EricRibeiro** [comment]
Thanks for making the changes and answering my question. The orb is looking good now!
